# Generated by Django 3.2.10 on 2021-12-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Enter Url adress', unique=True)),
                ('short_url', models.CharField(max_length=30)),
                ('click_time', models.IntegerField()),
            ],
        ),
    ]
